FROM ollama/ollama AS ollama

FROM cgr.dev/chainguard/wolfi-base
RUN apk add --no-cache libstdc++
COPY --from=ollama /usr/bin/ollama /usr/bin/ollama
COPY --from=ollama /usr/lib/ollama/runners/cpu /usr/lib/ollama/runners/cpu
RUN /usr/bin/ollama serve & sleep 5 && /usr/bin/ollama pull llama3.2
ENV OLLAMA_HOST=0.0.0.0
EXPOSE 11434
ENTRYPOINT ["/usr/bin/ollama"]
CMD ["serve"]